name: prcheck

on:
  push:
    branches: [master, next, ci]
  pull_request:
    branches: [master, next, ci]
  workflow_dispatch:

jobs:
  prcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: new entries
        run: .github/workflows/prcheck.sh
